#!/usr/bin/env bash


export SKIM_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'
export SKIM_DEFAULT_OPTIONS='--height 80% --border --reverse --bind=alt-n:down,alt-p:up,ctrl-n:page-down,ctrl-p:page-up,ctrl-k:kill-line'
alias skf="sk --ansi -i -c 'rg --color=always --line-number "{}"'"


# fh - repeat history
fh() {
  print -z "$(history | awk '{$1=""; print $0}' | sort | uniq -c | sort -nk1 | sk --tac --no-sort | sed -E 's/ *[0-9]*\*? *//' | sed -E 's/\\/\\\\/g')"
}

# fkill - kill processes - list only the ones you can kill. Modified the earlier script.
fkill() {
  local pid
  if [ "$UID" != "0" ]; then
    pid=$(ps -f -u $UID | sed 1d | sk -m | awk '{print $2}')
  else
    pid=$(ps -ef | sed 1d | sk -m | awk '{print $2}')
  fi

  if [ "x$pid" != "x" ]
  then
    echo "$pid" | xargs kill -"${1:-9}"
  fi
}

# Select a running docker container to stop
drs() {
  local cid
  cid=$(docker ps -a | sed 1d | sk -m | awk '{print $1}')

  echo "$cid" | xargs docker stop
}

drmi() {
  local iid
  iid=$(docker images | sed 1d | sk -m | awk '{print $3}')

  echo "$cid" | xargs docker rmi
}
