#!/usr/bin/env bash

PROXY_INTERFACE=$(networksetup -listallhardwareports \
    | grep -B1 "$(route get default | grep interface | awk '{print $2}')" \
    | grep "Hardware Port:" \
    | awk -F': ' '{print $2}')
PROXY_HOST="${1:-localhost}"
PROXY_PORT="${2:-7890}"

current_http_proxy_state=$(networksetup -getwebproxy "$PROXY_INTERFACE" | grep "^Enabled: " | awk '{print $2}')

if [ "$current_http_proxy_state" == "Yes" ]; then
    networksetup -setwebproxystate "$PROXY_INTERFACE" off
    networksetup -setsecurewebproxystate "$PROXY_INTERFACE" off
    networksetup -setsocksfirewallproxystate "$PROXY_INTERFACE" off
    echo "Disabled proxy for $PROXY_INTERFACE"
else
    networksetup -setwebproxy "$PROXY_INTERFACE" "$PROXY_HOST" "$PROXY_PORT"
    networksetup -setsecurewebproxy "$PROXY_INTERFACE" "$PROXY_HOST" "$PROXY_PORT"
    networksetup -setsocksfirewallproxy "$PROXY_INTERFACE" "$PROXY_HOST" "$PROXY_PORT"
    echo "Enabled proxy for $PROXY_INTERFACE: $PROXY_HOST:$PROXY_PORT"
fi
