ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=243"
bindkey ';;' autosuggest-accept


if [ -f ~/.bashrc ]; then
   source ~/.bashrc
fi


[[ -x "$(command -v zoxide)" ]] && eval "$(zoxide init zsh)" && alias cd=z

# export JAVA_HOME=$(asdf where java)

# export HOMEBREW_BREW_GIT_REMOTE="https://mirrors.ustc.edu.cn/brew.git"
# export HOMEBREW_CORE_GIT_REMOTE="https://mirrors.ustc.edu.cn/homebrew-core.git"
# export HOMEBREW_BOTTLE_DOMAIN="https://mirrors.ustc.edu.cn/homebrew-bottles"

