[keyboard]
bindings = [
  { key = "A",         mods = "Command",       chars = "\u001Ba"                       },
  { key = "B",         mods = "Command",       chars = "\u001Bb"                       },
  { key = "C",         mods = "Command",       chars = "\u001Bc"                       },
  { key = "D",         mods = "Command",       chars = "\u001Bd"                       },
  { key = "E",         mods = "Command",       chars = "\u001Be"                       },
  { key = "F",         mods = "Command",       chars = "\u001Bf"                       },
  { key = "G",         mods = "Command",       chars = "\u001Bg"                       },
  { key = "H",         mods = "Command",       chars = "\u001Bh"                       },
  { key = "I",         mods = "Command",       chars = "\u001Bi"                       },
  { key = "J",         mods = "Command",       chars = "\u001Bj"                       },
  { key = "K",         mods = "Command",       chars = "\u001Bk"                       },
  { key = "L",         mods = "Command",       chars = "\u001Bl"                       },
  { key = "M",         mods = "Command",       chars = "\u001Bm"                       },
  { key = "N",         mods = "Command",       chars = "\u001Bn"                       },
  { key = "O",         mods = "Command",       chars = "\u001Bo"                       },
  { key = "P",         mods = "Command",       chars = "\u001Bp"                       },
  { key = "Q",         mods = "Command",       chars = "\u001Bq"                       },
  { key = "R",         mods = "Command",       chars = "\u001Br"                       },
  { key = "S",         mods = "Command",       chars = "\u001Bs"                       },
  { key = "T",         mods = "Command",       chars = "\u001Bt"                       },
  { key = "U",         mods = "Command",       chars = "\u001Bu"                       },
  { key = "V",         mods = "Command",       chars = "\u001Bv"                       },
  { key = "W",         mods = "Command",       chars = "\u001Bw"                       },
  { key = "X",         mods = "Command",       chars = "\u001Bx"                       },
  { key = "Y",         mods = "Command",       chars = "\u001By"                       },
  { key = "Z",         mods = "Command",       chars = "\u001Bz"                       },
  { key = "A",         mods = "Command|Shift", chars = "\u001BA"                       },
  { key = "B",         mods = "Command|Shift", chars = "\u001BB"                       },
  { key = "C",         mods = "Command|Shift", chars = "\u001BC"                       },
  { key = "D",         mods = "Command|Shift", chars = "\u001BD"                       },
  { key = "E",         mods = "Command|Shift", chars = "\u001BE"                       },
  { key = "F",         mods = "Command|Shift", chars = "\u001BF"                       },
  { key = "G",         mods = "Command|Shift", chars = "\u001BG"                       },
  { key = "H",         mods = "Command|Shift", chars = "\u001BH"                       },
  { key = "I",         mods = "Command|Shift", chars = "\u001BI"                       },
  { key = "J",         mods = "Command|Shift", chars = "\u001BJ"                       },
  { key = "K",         mods = "Command|Shift", chars = "\u001BK"                       },
  { key = "L",         mods = "Command|Shift", chars = "\u001BL"                       },
  { key = "M",         mods = "Command|Shift", chars = "\u001BM"                       },
  { key = "N",         mods = "Command|Shift", chars = "\u001BN"                       },
  { key = "O",         mods = "Command|Shift", chars = "\u001BO"                       },
  { key = "P",         mods = "Command|Shift", chars = "\u001BP"                       },
  { key = "Q",         mods = "Command|Shift", chars = "\u001BQ"                       },
  { key = "R",         mods = "Command|Shift", chars = "\u001BR"                       },
  { key = "S",         mods = "Command|Shift", chars = "\u001BS"                       },
  { key = "T",         mods = "Command|Shift", chars = "\u001BT"                       },
  { key = "U",         mods = "Command|Shift", chars = "\u001BU"                       },
  { key = "V",         mods = "Command|Shift", chars = "\u001BV"                       },
  { key = "W",         mods = "Command|Shift", chars = "\u001BW"                       },
  { key = "X",         mods = "Command|Shift", chars = "\u001BX"                       },
  { key = "Y",         mods = "Command|Shift", chars = "\u001BY"                       },
  { key = "Z",         mods = "Command|Shift", chars = "\u001BZ"                       },
  { key = "Key1",      mods = "Command",       chars = "\u001B1"                       },
  { key = "Key2",      mods = "Command",       chars = "\u001B2"                       },
  { key = "Key3",      mods = "Command",       chars = "\u001B3"                       },
  { key = "Key4",      mods = "Command",       chars = "\u001B4"                       },
  { key = "Key5",      mods = "Command",       chars = "\u001B5"                       },
  { key = "Key6",      mods = "Command",       chars = "\u001B6"                       },
  { key = "Key7",      mods = "Command",       chars = "\u001B7"                       },
  { key = "Key8",      mods = "Command",       chars = "\u001B8"                       },
  { key = "Key9",      mods = "Command",       chars = "\u001B9"                       },
  { key = "Key0",      mods = "Command",       chars = "\u001B0"                       },

  # { key = "Grave",     mods = "Command",       chars = "\u001B`"                       }, # M-`
  # { key = "Tilde",     mods = "Command|Shift", chars = "\u001B~"                       }, # M-~
  { key = "Key1",      mods = "Command|Shift", chars = "\u001B!"                       },
  { key = "Key2",      mods = "Command|Shift", chars = "\u001B@"                       },
  { key = "Key3",      mods = "Command|Shift", chars = "\u001B#"                       },
  { key = "Key4",      mods = "Command|Shift", chars = "\u001B$"                       },
  { key = "Key5",      mods = "Command|Shift", chars = "\u001B%"                       },
  { key = "Key6",      mods = "Command|Shift", chars = "\u001B^"                       },
  { key = "Key7",      mods = "Command|Shift", chars = "\u001B&"                       },
  { key = "Key8",      mods = "Command|Shift", chars = "\u001B*"                       },
  { key = "Key9",      mods = "Command|Shift", chars = "\u001B("                       },
  { key = "Key0",      mods = "Command|Shift", chars = "\u001B)"                       },
  { key = "Minus",     mods = "Command",       chars = "\u001B-"                       }, # M--
  { key = "Minus",     mods = "Command|Shift", chars = "\u001B_"                       }, # M-_
  { key = "Equals",    mods = "Command",       chars = "\u001B="                       }, # M-=
  { key = "Equals",    mods = "Command|Shift", chars = "\u001B+"                       }, # M-+
  { key = "Backslash", mods = "Command",       chars = "\u001B\\"                      }, # M-\
  { key = "Backslash", mods = "Command|Shift", chars = "\u001B|"                       }, # M-|
  { key = "Semicolon", mods = "Command",       chars = "\u001B;"                       }, # M-;
  { key = "Semicolon", mods = "Command|Shift", chars = "\u001B:"                       }, # M-:
  # { key = "Apostrophe",mods = "Command",       chars = "\u001B'"                       }, # M-'
  # { key = "Apostrophe",mods = "Command|Shift", chars = "\u001B\""                      }, # M-"
  { key = "Comma",     mods = "Command",       chars = "\u001B,"                       }, # M-,
  { key = "Comma",     mods = "Command|Shift", chars = "\u001B<"                       }, # M-<
  { key = "Period",    mods = "Command",       chars = "\u001B."                       }, # M-.
  { key = "Period",    mods = "Command|Shift", chars = "\u001B>"                       }, # M->
  { key = "Slash",     mods = "Command",       chars = "\u001B/"                       }, # M-/
  { key = "Up",        mods = "Shift",         chars = "\u001B[1;2A"                   },
  { key = "Up",        mods = "Control",       chars = "\u001B[1;5A"                   },
  { key = "Up",        mods = "Command",       chars = "\u001B[1;3A"                   },
  { key = "Up",                              chars = "\u001B[A",   mode = "~AppCursor" },
  { key = "Up",                              chars = "\u001BOA",   mode = "AppCursor"  },
  { key = "Down",      mods = "Shift",         chars = "\u001B[1;2B"                   },
  { key = "Down",      mods = "Control",       chars = "\u001B[1;5B"                   },
  { key = "Down",      mods = "Command",       chars = "\u001B[1;3B"                   },
  { key = "Down",                            chars = "\u001B[B",   mode = "~AppCursor" },
  { key = "Down",                            chars = "\u001BOB",   mode = "AppCursor"  },
  { key = "Right",     mods = "Shift",         chars = "\u001B[1;2C"                   },
  { key = "Right",     mods = "Control",       chars = "\u001B[1;5C"                   },
  { key = "Right",     mods = "Command",       chars = "\u001B[1;3C"                   },
  { key = "Right",                           chars = "\u001B[C",   mode = "~AppCursor" },
  { key = "Right",                           chars = "\u001BOC",   mode = "AppCursor"  },
  { key = "Left",      mods = "Shift",         chars = "\u001B[1;2D"                   },
  { key = "Left",      mods = "Control",       chars = "\u001B[1;5D"                   },
  { key = "Left",      mods = "Command",       chars = "\u001B[1;3D"                   },
  { key = "Left",                            chars = "\u001B[D",   mode = "~AppCursor" },
  { key = "Left",                            chars = "\u001BOD",   mode = "AppCursor"  },

  # xxd -psd
  { key = "Q",         mods = "Control",       chars = "\u0011" }, # https://github.com/alacritty/alacritty/issues/1359#issuecomment-430265381
  { key = "Space",     mods = "Control",       chars = "\u0000"                        }, # C-SPC
  { key = "Slash",     mods = "Control",       chars = "\u001F"                        }, # C-/
  # https://stackoverflow.com/a/40222318
  { key = "Slash",     mods = "Control|Shift", chars = "\u001B[emacs-C-?" }, # ^[[emacs-C-?
  # Not work
  { key = "Slash",     mods = "Command|Shift", chars = "\u001B?" } # M-?
]